version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: packages/api-gateway/Dockerfile
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/api-gateway/node_modules
      - /app/packages/shared/node_modules
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
